// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClYKasVqO3z_6vPumYhDs7KUAPqPm032o',
    appId: '1:491504143482:web:22ca5413b948d55e3a3fc3',
    messagingSenderId: '491504143482',
    projectId: 'mamosis',
    authDomain: 'mamosis.firebaseapp.com',
    storageBucket: 'mamosis.firebasestorage.app',
    measurementId: 'G-DGEJK17EMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsV2-eE_LCuvILmqnXrAS3dvaWrEUvstU',
    appId: '1:491504143482:android:a467116a41e00a1c3a3fc3',
    messagingSenderId: '491504143482',
    projectId: 'mamosis',
    storageBucket: 'mamosis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6l8_PVvM9GMlLPLlRRCGDRoB9923qgWc',
    appId: '1:491504143482:ios:f2f9ac05e5f820993a3fc3',
    messagingSenderId: '491504143482',
    projectId: 'mamosis',
    storageBucket: 'mamosis.firebasestorage.app',
    iosBundleId: 'com.example.mamosis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6l8_PVvM9GMlLPLlRRCGDRoB9923qgWc',
    appId: '1:491504143482:ios:f2f9ac05e5f820993a3fc3',
    messagingSenderId: '491504143482',
    projectId: 'mamosis',
    storageBucket: 'mamosis.firebasestorage.app',
    iosBundleId: 'com.example.mamosis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClYKasVqO3z_6vPumYhDs7KUAPqPm032o',
    appId: '1:491504143482:web:78866c85e5f7f1d43a3fc3',
    messagingSenderId: '491504143482',
    projectId: 'mamosis',
    authDomain: 'mamosis.firebaseapp.com',
    storageBucket: 'mamosis.firebasestorage.app',
    measurementId: 'G-227EP3NRLV',
  );
}
